---
- hosts: ubuntu-server
  gather_facts: false
  become: true

    # Запрашиваем логин и пароль от удалённого хоста для подключения по SSH из зашифрованного файла vars.yaml 
  vars_files:
    - vars.yml

  tasks:

    # 
    # Описание модуля debconf: https://docs.ansible.com/ansible/2.8/modules/debconf_module.html
    - name: Set Postfix option hostname
      debconf: 
        name: postifx 
        question: "postfix/mailname" 
        value: "postfix-server" 
        vtype: "string"
      tags:
      - init_postfix

    # 
    - name: Set Postfix option type as internet site
      debconf: 
        name: postfix 
        question: "postfix/main_mailer_type" 
        value: "'Internet Site'" 
        vtype: "string"
      tags:
      - init_postfix

    # Установка postfix и mailutils
    # Описание модуля apt: https://docs.ansible.com/ansible/2.8/modules/apt_module.html#apt-module
    - name: Install Postfix
      apt: 
      apt: 
        name: "{{ packages }}"
        state: latest 
      vars:
        packages:
        - postfix
        - mailutils
      tags:
      - init_postfix

    # Настраиваем файервол для работы демона postfix
    # Описание модуля community.general.ufw: https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
    - name: Setting firewalld - ufw for postfix at ubuntu
      community.general.ufw:
        rule: allow
        name: postfix
      tags:
      - init_postfix

    # Запуск почтового демона
    # Описание модуля ansible.builtin.service: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
    - name: Run postfix server demon
      ansible.builtin.service:  
        name: postfix
        state: started
      tags:
      - init_postfix

    # Удаляем в файерволе разрешающее правило работы демона postfix
    # Описание модуля community.general.ufw: https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
    - name: Remove firewalld - ufw for postfix at ubuntu
      community.general.ufw:
        rule: reject
        name: postfix
      tags:
      - drop_postfix

    # Удаление postfix и mailutils
    # Описание модуля apt: https://docs.ansible.com/ansible/2.8/modules/apt_module.html#apt-module
    - name: Remove Postfix
      apt: 
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - postfix
        - mailutils
      tags:
      - drop_postfix



